### ISSUE TITLE
ScRNA-seq and bulk RNA-seq data format required to perform imputation

### ISSUE THREAD

**Issue by wuliRothschild** [XuYuanchi/Bis#1]
Hello, Bis Author! This algorithm looks good. What format of scRNA-seq data and bulk sequencing data do I need to input when performing imputation? Is it counts data, or needs to input cpm data similar to "data" layer of Seurat objects for scRNA-seq as well as tpm data for bulk sequencing?
Thanks！

**Comment by XuYuanchi** [comment]
Thank you very much for your interest in our work! For both scRNA-seq and bulk data, count data should be used as input. Afterward, normalization can be performed using _scanpy.pp.normalize_total_ for both datasets. If you have any further questions, feel free to reach out!
